// placeholders.js

export const templatePlaceholders = {
  "Sale Deed": [
    "Name of Colony",
    "Category of Colony",
    "Type of Property",
    "Minimum Rate of Land Notified by Govt. per Sq.Mtrs.",
    "Cost of Construction notified by Government in Sq.Mtrs.",
    "Total Flat Area in Sq.Mtrs.",
    "Number of Floors",
    "Lift provided or not",
    "Amount",
    "Year of Construction",
    "Age Factor",
    "Type of Colony",
    "Status of Building",
    "Use Factor",
  ],
  "Gift Deed": [
    "Name of Colony",
    "Category of Colony",
    "Type of Property",
    "Minimum Rate of Land Notified by Govt. per Sq.Mtrs.",
    "Cost of Construction notified by Government in Sq.Mtrs.",
    "Total Plot Area in Sq.Mtrs.",
    "Land Share under Transfer in Sq.Mtrs/Percentage",
    "Total Plinth Area/FAR in Sq.Mtrs.",
    "Plinth Area under Transfer",
    "Parking Area under Transfer (wherever applicable)",
    "Number of Floors",
    "Lift provided or not (wherever applicable)",
    "Year of Construction",
    "Age Factor",
    "Type of Colony",
    "Status of Building",
    "Use Factor",
  ],
  "TWO PARTIES": [
    "Name of Colony",
    "Category of Colony",
    "Type of Property",
    "Minimum Rate of Land Notified by Govt.",
    "Cost of Construction notified by Government",
    "Total covered area with open land sq.mtrs.",
    "Plinth area in sq.mtrs.",
    "Total Flat Area in Sq.Mtrs.",
    "Number of Floors",
    "Covered area of F Floor",
    "Covered area of S.Floor",
    "Lift Provided or not",
    "Year of Construction",
    "Age Factor",
    "Type of Colony",
    "Status of Building",
    "Use Factor",
    "Location / Land Mark",
  ],
  "BAYANA SAMPLE FINAL": [],
  "Will": [],
  "FAMILY WILL": [],
  "Rent Deed":[],
  "VEHICLE SALE AND PURTUESED-5": [],
};
